---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "Modélisation des changements de distribution hivernale du lièvre variable _Lepus timidus_ et du lièvre d’Europe _Lepus europaeus_ sur leur zone de contact en lien avec le changement climatique "
```

# Projet “Modèles de niche Lièvres sur les massifs alpins”

Ce dépôt contient les données issues du Parc National du Mercantour et
le code nécessaire pour organiser les données puis exécuter les modèles
de niche. Il a vocation à être ré-exécuté à partir de nouvelles données
obtenues sur ce territoire ou sur d’autres espaces protégés. Ce projet
s’inscrit dans le cadre d’une coopération entre l’OFfice Français de
la Biodiversité et le CEFE [lien vers le téléchargement du
rapport](https://professionnels.ofb.fr/fr/node/400) Le détail sur le
protocole (contexte, collecte des données etc.) est disponible à cette
adresse : [lien vers le téléchargement du
rapport](https://mybinder.org/v2/gh/TCouturier/lievres/master?urlpath=rstudio)

Ce projet a été initié le 17 février 2021.

### Auteurs

  - **COUTURIER Thibaut** (Centre d’Ecologie Fonctionnelle et Evolutive)
  - **MANSONS Jérôme** (Parc national du Mercantour)
  - **ASTRUC Guillelme** (Bioditoring)
  - **QUEROUE Maud** (Centre d’Ecologie Fonctionnelle et Evolutive)

## Contenu

Ce dossier d’analyses contient :

  - [:file\_folder: data](./data): Les données obtenues dans le
    Parc national du Mercantour utilisées lors de l’analyse. Les rasters
    obtenus sur l’emprise du Parc sont dans un sous-dossier “rasters”.
  - [:file\_folder: scripts](./scripts): Les scripts utilisés lors de l'analyse. Ils sont organisés en plusieurs étapes. 
  - [:file\_folder: outputs](./outputs): Les exports issus de l'analyse
